#!/usr/bin/env zsh
# shellcheck shell=bash

antigen use ohmyzsh/ohmyzsh

antigen theme moarram/headline@main

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen bundle iterm2

antigen bundle atuinsh/atuin@main

antigen apply
